task/task/Controllers/datumController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace task.Controllers
{
    public class datumController : Controller
    {
        DataEntry db = new DataEntry();
        public ActionResult Index()
        {
            var data = from p in db.categories

                       select p.categoryName;

            SelectList list = new SelectList(data);
            ViewBag.Roles = list;
            return View();
        }
        public ActionResult create ()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FileUpload(HttpPostedFileBase file)
        {
            string category = Request.Form["category"];

            if (file != null)
            {
                
               string ImageName = System.IO.Path.GetFileName(file.FileName);
               // string physicalPath = Server.MapPath("~/images/" + ImageName);
              //  string physicalPath = "~/" + category + "/" + ImageName; // your code goes here
                var path = Path.Combine(Server.MapPath("~/images/" + category), ImageName);
                string subpath = "~/images/" + category;
   

                bool exists = System.IO.Directory.Exists(Server.MapPath(subpath));

                if (!exists) {
                    System.IO.Directory.CreateDirectory(Server.MapPath(subpath));
                }
                   
                                

                // save image in folder
                file.SaveAs(path);
                

                //save new record in database
               datum newRecord = new datum();
                newRecord.category = Request.Form["category"];
                newRecord.description = Request.Form["description"];
                newRecord.imagePath = ImageName;
                db.data.Add(newRecord);
                db.SaveChanges();
               

            }
            //Display records
            return RedirectToAction("Display");
        }

        public ActionResult Display()
        {
            return View();
        }
	}
}

task/task/Views/datum/Display.cshtml
@model IEnumerable<task.datum>

@{
    ViewBag.Title = "Display";
}

<h2>Display</h2>
@{
    task.DataEntry db = new task.DataEntry();
}
@using (Html.BeginForm())
{
    <table border="1">
        <thead>
            <tr>
                <th>Image</th>
                <th>category</th>
                <th>description</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in db.data)
            {
                <tr>
                    <td><img src="~/images/@item.category/@item.imagePath" width="100" height="100" /></td>
                    <td>@item.category</td>
                    <td>@item.description</td>
                </tr>
            }
        </tbody>
    </table>
}

task/task/Views/datum/Index.cshtml
@model IEnumerable<task.datum>

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("FileUpload", "datum", FormMethod.Post,
                    new { enctype = "multipart/form-data" }))
{
    <div>
       category<br />
       @Html.DropDownList("category", ViewBag.Roles as SelectList)
     <br/>
       description<br />
        @Html.TextBox("description") <br />
        Image<br />
        <input type="File" name="file" id="file" value="Choose File" />
        <input type="submit" value="Upload" class="submit" />
    </div>
}